apiVersion: apps/v1
kind: Deployment
metadata:
  name: s3-upload-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: s3-upload-app
  template:
    metadata:
      labels:
        app: s3-upload-app
    spec:
      containers:
      - name: s3-upload-app
        image: etiquet/s3-upload-app:1.00
        ports:
        - containerPort: 5000
        env:
        - name: S3_BUCKET
          valueFrom:
            secretKeyRef:
              name: s3-upload-app-secret
              key: S3_BUCKET
        - name: S3_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: s3-upload-app-secret
              key: S3_ACCESS_KEY_ID
        - name: S3_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: s3-upload-app-secret
              key: S3_SECRET_ACCESS_KEY
        - name: S3_REGION
          valueFrom:
            secretKeyRef:
              name: s3-upload-app-secret
              key: S3_REGION
        - name: S3_URL
          valueFrom:
            secretKeyRef:
              name: s3-upload-app-secret
              key: S3_URL
